[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
logfile_maxbytes=10MB
loglevel=info

[program:ml-service]
command=uvicorn main:app --host 0.0.0.0 --port 8000
directory=/app/ml-service
autostart=true
autorestart=true
stdout_logfile=/app/logs/ml-service.log
stderr_logfile=/app/logs/ml-service.log

[program:server]
command=node server.js
directory=/app/server
autostart=true
autorestart=true
stdout_logfile=/app/logs/server.log
stderr_logfile=/app/logs/server.log
